In [69]:
import struct
import cv2
import numpy as np
import matplotlib.pyplot as plt 
from IPython.display import Image, display

problem = '''
8--------
--36-----
-7--9-2--
-5---7---
----457--
---1---3-
--1----68
--85---1-
-9----4--
'''

def sudoku_solve(problem):
    rows, cols = problem.shape
    all_nums = set([i for i in range(0, 10)])
    for i in range(rows):
        for j in range(cols):
            if problem[i, j] == 0:
                # 候補の数字を調べる (以下のnumsに代入する)
                k = 3 * (i // 3)
                l = 3 * (j // 3)
                blk_nums = problem[k:k+3, l:l+3]
                row_nums = problem[i,:]
                col_nums = problem[:,j]
                used_nums = set(row_nums.tolist() + col_nums.tolist() + blk_nums.flatten().tolist())
                nums = set([i for i in range(10)]).difference(used_nums)

                # 候補の数字を仮入れして再帰呼び出し
                success = False
                for n in nums:
                    # 数字を代入
                    problem[i, j] = n
                    if sudoku_solve(problem):
                        success = True
                        break

                    # 失敗したら元に戻す
                    problem[i, j] = 0

                if not success:
                    return False
        
    return True


problem = problem.split('\n')
problem = [line for line in problem if line != '']
problem = [c for line in problem for c in line]
numbers = {'-': 0}
numbers.update({str(i): i for i in range(1, 10)})
problem = [numbers[c] for line in problem for c in line]
#print(numbers)

#9*9の２次元配列に変換
problem = np.array(problem).reshape(9,9)
print(problem)

sudoku_solve(problem)
print(problem)


[[8 0 0 0 0 0 0 0 0]
 [0 0 3 6 0 0 0 0 0]
 [0 7 0 0 9 0 2 0 0]
 [0 5 0 0 0 7 0 0 0]
 [0 0 0 0 4 5 7 0 0]
 [0 0 0 1 0 0 0 3 0]
 [0 0 1 0 0 0 0 6 8]
 [0 0 8 5 0 0 0 1 0]
 [0 9 0 0 0 0 4 0 0]]
[[8 1 2 7 5 3 6 4 9]
 [9 4 3 6 8 2 1 7 5]
 [6 7 5 4 9 1 2 8 3]
 [1 5 4 2 3 7 8 9 6]
 [3 6 9 8 4 5 7 2 1]
 [2 8 7 1 6 9 5 3 4]
 [5 2 1 9 7 4 3 6 8]
 [4 3 8 5 2 6 9 1 7]
 [7 9 6 3 1 8 4 5 2]]
